version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ODOO_DB
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    volumes:
      - ../data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  odoo:
    image: odoo:19
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - ../custom_addons:/mnt/extra-addons
      - ../logs:/var/log/odoo
      - ../odoo/debian/odoo.conf:/etc/odoo/odoo.conf
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
      - DB=ODOO_DB
